/**
 *FUNCTION TO GET MESSAGE FROM QUEUE WHICH IS SEND WITH DELAY OF 5 MINS
 ONCE MESSAGES IS PUBLISH IN QUEUE THIS FUNCTION WILL READ THE MESSAGE AND
 END THE ONGOING REQUEST AND CHANGE THE STATUS TO COMPLETED AND RELEASE DRIVER TO GET ANOTHER REQUEST
*/

function readQueue() {

}
//THIS FUNCTION WILL BE CALLED INTERNALLY WHEN EVER ANY MESSAGE IS RECEIVED IN QUEUE
function updateRequest() {
  //GET ONGOING REQUEST
  const query = {

  };
}
